;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        backward-sexp
        beginning-of-visual-line
        comment-dwim
        end-of-visual-line
        evilmi-jump-items
        forward-sexp
        indent-for-tab-command
        kill-region-or-word
        kill-visual-line
        mark-sexp
        markdown-outdent-or-delete
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-self-insert-command
        org-yank
        paredit-forward
        paredit-forward-kill-word
        paredit-kill-region-or-word
        paredit-open-round
        paredit-semicolon
        sp-backward-delete-char
        sp-delete-char
        sp-forward-barf-sexp
        sp-forward-slurp-sexp
        transpose-sexps
        transpose-words
        tuareg-comment-dwim
        tuareg-electric-pipe
        tuareg-indent-phrase
        typescript-insert-and-indent
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        iedit-switch-to-mc-mode
        tuareg-electric-rp
        undo-tree-visualize
        ))
