;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        beginning-of-visual-line
        comment-dwim
        end-of-visual-line
        org-self-insert-command
        typescript-insert-and-indent
        ))

(setq mc/cmds-to-run-once
      '(
        iedit-switch-to-mc-mode
        ))
