;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        beginning-of-visual-line
        comment-dwim
        end-of-visual-line
        kill-region-or-word
        org-delete-char
        org-end-of-line
        org-self-insert-command
        org-yank
        tuareg-comment-dwim
        tuareg-indent-phrase
        typescript-insert-and-indent
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        iedit-switch-to-mc-mode
        undo-tree-visualize
        ))
